# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='type_p',
            field=models.CharField(default='Измеритель объема', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='type_s',
            field=models.CharField(default='Газоотделитель', max_length=300),
        ),
    ]
