# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_auto_20170921_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('title', models.CharField(default='Измеритель объема', max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('title', models.CharField(default='Газоотделитель', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='production',
            name='type_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelist.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelist.ServiceCategory'),
        ),
    ]
