# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_auto_20170922_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='info',
            field=models.CharField(default='Измеритель объема. Важная деталь ТРК. Служит для определения выдаваемого количества (дозы, объема) топлива.Большинство объемомеров – поршневого типа.', max_length=600),
        ),
    ]
