# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_productcategory_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='info',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
